---
# nextcloud volume mounting and configuration
#
# We're only concering ourselves with this once. After the initial install,
# changing the data directory becomes a bit tedious. So the plan here is, get
# it right the first time, and if there's a need to do it multiple times or on
# many boxes, this is probably not the right tool.
#
# @see https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition#if-you-just-installed-the-snap-and-havent-created-an-admin-user-yet

- name: "Set non-snap nextcloud data directory fact."
  set_fact:
    nc_snap_nextcloud_data_dir: "{{ nc_snap_nextcloud_dir }}/data"

- name: "Ensure correct file permissions of data directory."
  file:
    path: "{{ nc_snap_nextcloud_dir }}"
    owner: "root"
    group: "root"
    mode: "0775"
    recurse: true

- name: "Ensure non-snap nextcloud data directory exists."
  file:
    path: "{{ nc_snap_nextcloud_data_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0775"

- name: "Set the nextcloud data directory path in autoconfig.php."
  lineinfile:
    path: "/var/snap/nextcloud/current/nextcloud/config/autoconfig.php"
    regexp: "^'directory'"
    line: "'directory' => '{{ nc_snap_nextcloud_data_dir }}',"
    create: false

- name: "Restart the PHP service."
  command: "snap restart nextcloud.php-fpm"

- name: "Refresh the homepage."
  url:
    url: "http://127.0.0.1:80/index.php"
    dest: "/tmp/index.php"
