---
# nextcloud volume mounting and configuration

- name: "Ensure non-snap nextcloud data directory exists."
  file:
    path: "{{ nc_snap_nextcloud_data_dir }}"
    state: directory
    owner: "root"
    group: "root"

- name: "Determine the current nextcloud data directory path."
  command: "nextcloud.occ config:system:get datadirectory"
  register: configured_datadirectory
  changed_when: false

- name: "Set non-snap nextcloud data directory."
  command: "nextcloud.occ config:system:set datadirectory {{ nc_snap_nextcloud_data_dir }}"
  when: "configured_datadirectory.stdout != nc_snap_nextcloud_data_dir"
