---
# nextcloud trusted domains configuration for ansible-role-nextcloud-snap

- name: "Retrieve the list of nextcloud trusted domains."
  ansible.builtin.command: "nextcloud.occ config:system:get trusted_domains"
  register: nextcloud_trusted_domains
  changed_when: false

- name: "Set trusted domain."
  ansible.builtin.command: >
    nextcloud.occ config:system:set trusted_domains
      {{ index }} --value={{ domain }}
  loop: "{{ nc_snap_trusted_domains }}"
  loop_control:
    index_var: index
    loop_var: domain
  when: "nc_snap_trusted_domains != nextcloud_trusted_domains.stdout_lines"
