---
# nextcloud app installation for ansible-role-nextcloud-app

- name: "Get Nextcloud app status."
  ansible.builtin.command: "nextcloud.occ status"
  register: nextcloud_app_status
  changed_when: false

- name: "Manually install Nextcloud."
  ansible.builtin.command: >
    nextcloud.manual-install
    -d {{ nc_snap_nextcloud_data_dir|default('/var/snap/nextcloud/common/nextcloud/data') }}
    {{ nc_snap_admin_user|quote }}
    {{ nc_snap_admin_password|quote }}
  when: "'installed: true' not in nextcloud_app_status.stdout"
