---
# dependency installation for ansible-role-nextcloud-snap

- name: "Ensure that it's possible to install the Nextcloud snap."
  apt:
    name:
      - "certbot"
      - "snapd"
    state: "present"
    update_cache: true

- name: "Install Nextcloud snap."
  community.general.snap:
    name: "nextcloud"
    classic: false
    channel: "{{ nc_snap_install_channel }}"
