---
# nextcloud app installation for ansible-role-nextcloud-app

- name: "Manually install Nextcloud."
  command: >
    nextcloud.manual-install
      {{ nc_snap_admin_user }}
      {{ nc_snap_admin_password }}
