---
# tasks file for ansible-role-nextcloud-snap

- name: "Install nextcloud snap."
  include_tasks: "install-nextcloud-snap.yml"

- name: "Install nextcloud app."
  include_tasks: "install-nextcloud-app.yml"

- name: "Configure nextcloud volumes."
  include_tasks: "configure-nextcloud-volumes.yml"

- name: "Configure nextcloud trusted domains."
  include_tasks: "configure-nextcloud-trusted-domains.yml"

- name: "Configure nextcloud https and ssl certificates."
  include_tasks: "configure-nextcloud-https.yml"
