---
# tasks file for ansible-role-nextcloud-snap

- name: "Install nextcloud snap."
  ansible.builtin.import_tasks: "install-nextcloud-snap.yml"

- name: "Install nextcloud app."
  ansible.builtin.import_tasks: "install-nextcloud-app.yml"

- name: "Configure nextcloud trusted domains."
  ansible.builtin.import_tasks: "configure-nextcloud-trusted-domains.yml"

- name: "Configure nextcloud https and ssl certificates."
  ansible.builtin.import_tasks: "configure-nextcloud-https.yml"

- name: "Run postinstall or maintenance nextcloud commands."
  ansible.builtin.import_tasks: "run-nextcloud-commands.yml"
