---
# tasks file for ansible-role-nextcloud-snap

- name: "Install nextcloud snap."
  import_tasks: "install-nextcloud-snap.yml"

- name: "Get Nextcloud app status."
  command: "nextcloud.occ status"
  register: nextcloud_app_status
  changed_when: false

- name: "Configure nextcloud storage."
  import_tasks: "configure-nextcloud-storage.yml"
  when:
    - "'installed: true' not in nextcloud_app_status.stdout"
    - "nc_snap_nextcloud_dir is defined"

- name: "Install nextcloud app."
  import_tasks: "install-nextcloud-app.yml"
  when:
    - "'installed: true' not in nextcloud_app_status.stdout"

- name: "Configure nextcloud trusted domains."
  import_tasks: "configure-nextcloud-trusted-domains.yml"

- name: "Configure nextcloud https and ssl certificates."
  import_tasks: "configure-nextcloud-https.yml"

- name: "Run postinstall or maintenance nextcloud commands."
  import_tasks: "run-nextcloud-commands.yml"
