---
# tasks file for ansible-role-nextcloud-snap

- name: "Install nextcloud snap."
  import_tasks: "install-nextcloud-snap.yml"

- name: "Configure nextcloud volumes."
  import_tasks: "configure-nextcloud-storage.yml"

- name: "Install nextcloud app."
  import_tasks: "install-nextcloud-app.yml"

- name: "Configure nextcloud trusted domains."
  import_tasks: "configure-nextcloud-trusted-domains.yml"

- name: "Configure nextcloud https and ssl certificates."
  import_tasks: "configure-nextcloud-https.yml"
  tags:
    - notest

- name: "Run postinstall or maintenance nextcloud commands."
  import_tasks: "run-nextcloud-commands.yml"
